version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      - MONGO_DB=testdb2
